### PR TITLE
Feature/6120 dumpconfig fix

### PR DESCRIPTION
**Pull request by odain-cbd**
Same dump XML config fix with test.

### CODE REVIEW

**Comment by Hipska** [comment]
Can you please fix the conflict, it seems it cannot be done on GitHub but needs to be done on the branch locally.

(I merged master into config-dump branch in order to reduce the commits.)

**Comment by odain-cbd** [comment]
merge almost finished. please give me write access to do so?
`remote: Permission to Super-Visions/itop-data-collector-base.git denied to odain-cbd.`

**Comment by Hipska** [comment]
No, you need to push it to **Combodo:feature/6120-dumpconfig-fix** of course 😉 

Otherwise, I can also try to manually cherry pick them on my branch..

**Comment by odain-cbd** [comment]
ok i just did it.

**Review by Hipska — APPROVED** [review]

**Pull request merged**
